# Generated by Django 5.1.7 on 2025-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipie_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('ingrediants', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='pic')),
                ('instructions', models.CharField(max_length=30)),
            ],
        ),
    ]
